name: mind_lift
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4  # Use the latest version available
  shared_preferences: ^2.0.12
  path_provider: ^2.0.2
  provider: ^6.0.5
  fl_chart: ^0.64.0
  table_calendar: ^3.0.9
  flutter_local_notifications: ^16.3.2
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  sqflite: ^2.3.0
  path: ^1.8.3
  crypto: ^3.0.3
  flutter_sound: ^9.4.6 # for easier sound grabbing
  rxdart: ^0.27.7
  tflite_flutter: ^0.10.4
  intl: ^0.19.0
  url_launcher: ^6.2.6

  flutter_foreground_task: ^6.1.3 # For running the audio grabber

  # Custom plugin
  audio_to_float_array:
    path: ./audio_to_float_array

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  timezone: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/purplebg.jpg
    - assets/ML.png
    - assets/model.tflite
    - assets/vocab.json
    - assets/YAMnetModel.tflite
    - assets/audioLabels.txt

  fonts:
    - family: Billabong
      fonts:
        - asset: fonts/Billabong.otf

    - family: OliveRemaine
      fonts:
        - asset: fonts/OliveRemaine.otf
